#ifndef NODEMCU_BMP280_WEBTHING_FLOWER_HUMIDITY_H
#define NODEMCU_BMP280_WEBTHING_FLOWER_HUMIDITY_H

#define MIN_PERCENT 0
#define MAX_PERCENT 100
#define MAX_ANALOG_READ 1024
#define MIN_ANALOG_READ 450
#endif //NODEMCU_BMP280_WEBTHING_FLOWER_HUMIDITY_H

double read_flowHum_humidity();